export interface TarotCard {
  id: number
  name: string
  upright: string
  inverse: string
}

export const TAROT_DECK: TarotCard[] = [
  { id: 0, name: "The Fool", upright: "Beginnings, innocence, spontaneity, free spirit", inverse: "Recklessness, risk-taking, foolishness, naivety" },
  { id: 1, name: "The Magician", upright: "Manifestation, resourcefulness, power, inspired action", inverse: "Manipulation, poor planning, untapped talents" },
  { id: 2, name: "The High Priestess", upright: "Intuition, sacred knowledge, divine feminine, subconscious", inverse: "Secrets, disconnection from intuition, withdrawal" },
  { id: 3, name: "The Empress", upright: "Femininity, beauty, nature, nurturing, abundance", inverse: "Dependence, smothering, emptiness, creative block" },
  { id: 4, name: "The Emperor", upright: "Authority, structure, control, fatherhood", inverse: "Domination, rigidity, inflexibility, lack of discipline" },
  { id: 5, name: "The Hierophant", upright: "Tradition, spiritual wisdom, conformity, religious beliefs", inverse: "Rebellion, unconventional approaches, freedom" },
  { id: 6, name: "The Lovers", upright: "Love, harmony, relationships, choices, alignment", inverse: "Disharmony, imbalance, misalignment of values" },
  { id: 7, name: "The Chariot", upright: "Control, willpower, success, determination", inverse: "Lack of direction, aggression, scattered energy" },
  { id: 8, name: "Strength", upright: "Courage, persuasion, influence, inner power", inverse: "Self-doubt, weakness, insecurity, raw emotion" },
  { id: 9, name: "The Hermit", upright: "Soul-searching, introspection, inner guidance", inverse: "Isolation, loneliness, withdrawal, lost" },
  { id: 10, name: "Wheel of Fortune", upright: "Change, cycles, inevitable fate, turning point", inverse: "Bad luck, resistance to change, breaking cycles" },
  { id: 11, name: "Justice", upright: "Fairness, truth, cause and effect, law", inverse: "Unfairness, dishonesty, lack of accountability" },
  { id: 12, name: "The Hanged Man", upright: "Sacrifice, release, perspective, suspension", inverse: "Stalling, indecision, stagnation" },
  { id: 13, name: "Death", upright: "Endings, change, transformation, transition", inverse: "Resistance to change, stagnation, decay" },
  { id: 14, name: "Temperance", upright: "Balance, moderation, patience, purpose", inverse: "Imbalance, excess, self-healing, re-alignment" },
  { id: 15, name: "The Devil", upright: "Bondage, addiction, materialism, playfulness", inverse: "Releasing limiting beliefs, freedom, reclaiming control" },
  { id: 16, name: "The Tower", upright: "Sudden change, upheaval, chaos, revelation", inverse: "Avoiding disaster, fear of change, internal disruption" },
  { id: 17, name: "The Star", upright: "Hope, faith, renewal, spirituality", inverse: "Despair, lack of faith, disconnection" },
  { id: 18, name: "The Moon", upright: "Illusion, fear, subconscious, intuition", inverse: "Release of fear, inner confusion, truth revealed" },
  { id: 19, name: "The Sun", upright: "Joy, success, celebration, positivity", inverse: "Temporary depression, lack of success, postponed joy" },
  { id: 20, name: "Judgement", upright: "Rebirth, inner calling, absolution, reckoning", inverse: "Self-doubt, avoiding truth, refusal of change" },
  { id: 21, name: "The World", upright: "Completion, achievement, fulfillment, wholeness", inverse: "Incompletion, delays, lack of closure" },
  { id: 22, name: "Ace of Wands", upright: "Inspiration, new opportunities, action, potential", inverse: "Delays, lack of motivation, missed opportunity" },
  { id: 23, name: "Two of Wands", upright: "Planning, making decisions, leaving comfort", inverse: "Fear of unknown, lack of planning, playing safe" },
  { id: 24, name: "Three of Wands", upright: "Expansion, foresight, momentum, progress", inverse: "Delays, obstacles, frustration, limited vision" },
  { id: 25, name: "Four of Wands", upright: "Celebration, harmony, home, community", inverse: "Lack of support, transition, conflict at home" },
  { id: 26, name: "Five of Wands", upright: "Conflict, competition, tension, diversity", inverse: "Avoiding conflict, inner conflict, compromise" },
  { id: 27, name: "Six of Wands", upright: "Victory, success, public recognition, confidence", inverse: "Failure, ego, lack of recognition, fallen from grace" },
  { id: 28, name: "Seven of Wands", upright: "Challenge, defense, protection, perseverance", inverse: "Giving up, overwhelmed, exhaustion, yielding" },
  { id: 29, name: "Eight of Wands", upright: "Speed, movement, rapid change, action", inverse: "Delays, frustration, holding back, stalling" },
  { id: 30, name: "Nine of Wands", upright: "Resilience, courage, persistence, last stand", inverse: "Exhaustion, defensiveness, paranoia, giving up" },
  { id: 31, name: "Ten of Wands", upright: "Burden, responsibility, hard work, stress", inverse: "Release, delegation, burnout, letting go" },
  { id: 32, name: "Page of Wands", upright: "Exploration, excitement, free spirit, messenger", inverse: "Lack of direction, hesitation, delays, cancellation" },
  { id: 33, name: "Knight of Wands", upright: "Energy, passion, adventure, impulsiveness", inverse: "Haste, recklessness, scattered energy, delays" },
  { id: 34, name: "Queen of Wands", upright: "Confidence, determination, charm, vibrant", inverse: "Insecurity, jealousy, demands, self-doubt" },
  { id: 35, name: "King of Wands", upright: "Leadership, vision, boldness, charisma", inverse: "Ruthlessness, dictatorship, impulsive, impatience" },
  { id: 36, name: "Ace of Cups", upright: "Compassion, love, new relationships, intuition", inverse: "Emotional block, repressed feelings, emptiness" },
  { id: 37, name: "Two of Cups", upright: "Unity, partnership, connection, soulmate", inverse: "Imbalance, broken communication, tension, divorce" },
  { id: 38, name: "Three of Cups", upright: "Friendship, celebration, teamwork, community", inverse: "Overindulgence, gossip, isolation, third-party" },
  { id: 39, name: "Four of Cups", upright: "Apathy, contemplation, re-evaluation, boredom", inverse: "Acceptance, new opportunities, awareness, seizing" },
  { id: 40, name: "Five of Cups", upright: "Loss, grief, regret, disappointment", inverse: "Acceptance, moving on, forgiveness, finding peace" },
  { id: 41, name: "Six of Cups", upright: "Nostalgia, childhood, innocence, reunion", inverse: "Stuck in past, naivety, unrealistic, moving forward" },
  { id: 42, name: "Seven of Cups", upright: "Opportunities, choices, illusion, fantasy", inverse: "Clarity, decisiveness, reality check, focus" },
  { id: 43, name: "Eight of Cups", upright: "Withdrawal, leaving, seeking, moving on", inverse: "Return, fear of change, stagnation, aimless" },
  { id: 44, name: "Nine of Cups", upright: "Contentment, satisfaction, wish fulfillment", inverse: "Dissatisfaction, materialism, arrogance, greed" },
  { id: 45, name: "Ten of Cups", upright: "Happiness, joy, alignment, family", inverse: "Disconnection, misalignment, broken home, conflict" },
  { id: 46, name: "Page of Cups", upright: "Creativity, intuition, messages, sensitivity", inverse: "Emotional instability, immaturity, creativity block" },
  { id: 47, name: "Knight of Cups", upright: "Romance, charm, idealism, following heart", inverse: "Moodiness, disappointment, unreliable, unrealistic" },
  { id: 48, name: "Queen of Cups", upright: "Compassion, calm, emotional security, healer", inverse: "Insecurity, dependence, emotional manipulation" },
  { id: 49, name: "King of Cups", upright: "Emotional maturity, calm, diplomatic, balanced", inverse: "Emotional manipulation, coldness, volatility, moodiness" },
  { id: 50, name: "Ace of Swords", upright: "Clarity, breakthrough, truth, new idea", inverse: "Confusion, misinformation, poor judgment, clouded" },
  { id: 51, name: "Two of Swords", upright: "Stalemate, difficult choice, avoidance, truce", inverse: "Indecision, confusion, information overload, release" },
  { id: 52, name: "Three of Swords", upright: "Heartbreak, sorrow, grief, sadness", inverse: "Recovery, forgiveness, moving on, healing" },
  { id: 53, name: "Four of Swords", upright: "Rest, contemplation, recuperation, meditation", inverse: "Restlessness, burnout, exhaustion, re-engaging" },
  { id: 54, name: "Five of Swords", upright: "Conflict, defeat, win at all costs, tension", inverse: "Reconciliation, compromise, moving on, forgiveness" },
  { id: 55, name: "Six of Swords", upright: "Transition, moving on, leaving behind, travel", inverse: "Stagnation, resistance, unfinished business, stuck" },
  { id: 56, name: "Seven of Swords", upright: "Deception, strategy, stealth, cunning", inverse: "Confession, coming clean, conscience, exposure" },
  { id: 57, name: "Eight of Swords", upright: "Restriction, feeling trapped, powerless, victim", inverse: "Self-acceptance, freedom, new perspective, release" },
  { id: 58, name: "Nine of Swords", upright: "Anxiety, nightmares, fear, paranoia", inverse: "Hope, recovery, overcoming fears, release" },
  { id: 59, name: "Ten of Swords", upright: "Painful endings, betrayal, rock bottom, collapse", inverse: "Recovery, survival, worst is over, regeneration" },
  { id: 60, name: "Page of Swords", upright: "Curiosity, new ideas, vigilance, messenger", inverse: "Deception, haste, all talk, scattered thoughts" },
  { id: 61, name: "Knight of Swords", upright: "Ambition, action, impulsiveness, drive", inverse: "No direction, recklessness, unyielding, impulsive" },
  { id: 62, name: "Queen of Swords", upright: "Independent, objective, articulate, sharp", inverse: "Cold, harsh, bitter, overly critical" },
  { id: 63, name: "King of Swords", upright: "Authority, truth, intellect, logical", inverse: "Manipulation, cruelty, abusive power, tyrant" },
  { id: 64, name: "Ace of Pentacles", upright: "Opportunity, prosperity, new venture, security", inverse: "Missed chance, scarcity, lack of planning, bad investment" },
  { id: 65, name: "Two of Pentacles", upright: "Balance, adaptability, juggling, prioritizing", inverse: "Imbalance, disorganization, overwhelm, taking too much" },
  { id: 66, name: "Three of Pentacles", upright: "Teamwork, collaboration, building, planning", inverse: "Lack of teamwork, disorganization, conflict, working alone" },
  { id: 67, name: "Four of Pentacles", upright: "Security, control, holding on, conservation", inverse: "Greed, materialism, letting go, fear of loss" },
  { id: 68, name: "Five of Pentacles", upright: "Hardship, insecurity, poverty, isolation", inverse: "Recovery, improvement, finding help, turning a corner" },
  { id: 69, name: "Six of Pentacles", upright: "Generosity, charity, giving, sharing", inverse: "Inequality, selfishness, strings attached, debt" },
  { id: 70, name: "Seven of Pentacles", upright: "Patience, investment, hard work, long-term view", inverse: "Impatience, lack of reward, wasted effort, giving up" },
  { id: 71, name: "Eight of Pentacles", upright: "Diligence, mastery, skill, apprenticeship", inverse: "Perfectionism, lack of focus, no ambition, short-cuts" },
  { id: 72, name: "Nine of Pentacles", upright: "Abundance, luxury, self-sufficiency, financial independence", inverse: "Over-investment, superficiality, dependence, false wealth" },
  { id: 73, name: "Ten of Pentacles", upright: "Wealth, legacy, family, long-term security", inverse: "Financial failure, loss of legacy, family conflict, poverty" },
  { id: 74, name: "Page of Pentacles", upright: "Studious, ambitious, new venture, opportunity", inverse: "Procrastination, lack of focus, missed opportunity, laziness" },
  { id: 75, name: "Knight of Pentacles", upright: "Hard work, routine, patience, diligence", inverse: "Boredom, stagnation, laziness, lack of progress" },
  { id: 76, name: "Queen of Pentacles", upright: "Nurturing, practical, grounded, financially secure", inverse: "Smothering, workaholic, financially insecure, neglect" },
  { id: 77, name: "King of Pentacles", upright: "Wealth, discipline, abundance, grounded", inverse: "Greed, materialism, stubbornness, controlling" },
  { id: 78, name: "Card Back", upright: "Unknown, mystery, potential, face down", inverse: "Unknown, mystery, potential, face down" }
]
